export const actions = {
  profile: {
    DATA_FETHING: 'PROFILE_DATA_FETHING',
    DATA_FETCHED: 'PROFILE_DATA_FETCHED',
    DATA_FETCH_ERROR: 'PROFILE_DATA_FETCH_ERROR',
    USER_DATA_EDITED: 'PROFILE_USER_DATA_EDITED',
    IMAGE_UPLOADED: 'PROFILE_IMAGE_UPLOADED'
  }
}
